import Config

truthy_env? = fn name ->
  case System.get_env(name) do
    value when value in ["1", "true", "TRUE", "yes", "YES", "on", "ON"] -> true
    _ -> false
  end
end

allow_remote_dev = truthy_env?.("ALLOW_REMOTE_DEV")

dev_secret_key_base =
  System.get_env("DEV_SECRET_KEY_BASE") ||
    "Wgx4re9bAGL0ZfA5TsZau0pKZTJSbhEaHF2BVCM5CFZe/UrwNn4tiBsDqtrTnW2g"

dev_check_origin =
  if allow_remote_dev do
    false
  else
    [
      "http://localhost",
      "http://127.0.0.1",
      "http://[::1]",
      "https://localhost",
      "https://127.0.0.1",
      "https://[::1]"
    ]
  end

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :portfolio_live, PortfolioLiveWeb.Endpoint,
  url: [host: "localhost", port: 4000, scheme: "http"],
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: [
    "http://localhost:4000",
    "http://127.0.0.1:4000"
  ],
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "Wgx4re9bAGL0ZfA5TsZau0pKZTJSbhEaHF2BVCM5CFZe/UrwNn4tiBsDqtrTnW2g",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:portfolio_live, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:portfolio_live, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :portfolio_live, PortfolioLiveWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Gettext translations
      ~r"priv/gettext/.*\.po$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/portfolio_live_web/router\.ex$"E,
      ~r"lib/portfolio_live_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :portfolio_live, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  debug_heex_annotations: true,
  debug_attributes: true,
  enable_expensive_runtime_checks: true

config :phoenix_live_view, :colocated_js, disable_symlink_warning: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
